# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ben Usman (aka MInner)
tagline:          'Math, machine learning, physics, lingustics and whatever'
description:      'Some insirational text here'

paginate:         5

#
sidebar:
  Home: 		  '/'
  About: 		  '/about'
  Archive: 		  '/archive'